# Generated by Django 3.0.6 on 2020-07-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200722_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
