# Generated by Django 3.0.6 on 2020-07-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200722_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
